---
openapi: 3.0.2
info:
  version: 1.0.0
  title: Cloud Storage Handler
  description: API for handling files on a cloud storage service
  contact:
    name: ELIXIR Cloud & AAI
    email: cloud-service@elixir-europe.org
  license:
    name: Apache 2.0
    url: >
      https://github.com/elixir-cloud-aai/
      cloud-storage-handler/blob/main/LICENSE
servers:
  - url: /elixircoud/csh/v1
paths:
  /:
    get:
      description: |
        Returns a welcome message
      operationId: home
      responses:
        '200':
          description: basic response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to Cloud Storage Handler API"
        '400':
          description: The request is malformed.
        '500':
          description: An unexpected error occurred.
  /object:
    post:
      description: |
        Create a new object upload using the TUS protocol. The request creates an empty object and returns an upload URL.
      operationId: upload_object
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  description: The file to be uploaded (supports .bib, .txt, .docx, and other file types).
      responses:
        '201':
          description: Object upload created successfully.
          headers:
            Location:
              schema:
                type: string
              description: URL to upload object chunks using PATCH requests.
            Tus-Resumable:
              schema:
                type: string
              description: Version of the TUS protocol used.
        '400':
          description: Bad request or malformed request body.
        '500':
          description: An unexpected error occurred.
...
