---
openapi: 3.0.2
info:
  version: 1.0.0
  title: Cloud Storage Handler
  description: API for handling files on a cloud storage service
  contact:
    name: ELIXIR Cloud & AAI
    email: cloud-service@elixir-europe.org
  license:
    name: Apache 2.0
    url: >
      https://github.com/elixir-cloud-aai/
      cloud-storage-handler/blob/main/LICENSE
servers:
  - url: /elixircoud/csh/v1
paths:
  /:
    get:
      description: |
        Returns a welcome message
      operationId: home
      responses:
        '200':
          description: basic response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to Cloud Storage Handler API"
        '400':
          description: The request is malformed.
        '500':
          description: An unexpected error occurred.
  /upload/initiate:
    post:
      summary: Initiate TUS upload session
      operationId: initiate_upload
      tags:
        - Upload
      responses:
        "201":
          description: TUS upload session initiated
          content:
            application/json:
              schema:
                type: object
                properties:
                  object_id:
                    type: string
                    description: Unique identifier for the upload session
  /upload/{object_id}/chunk:
    patch:
      summary: Upload a file chunk
      operationId: upload_chunk
      tags:
        - Upload
      parameters:
        - in: path
          name: object_id
          required: true
          schema:
            type: string
          description: Unique identifier for the upload session
      requestBody:
        required: true
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        "204":
          description: Chunk uploaded successfully
        "404":
          description: File not found
  /upload/complete/{object_id}:
    post:
      summary: Complete upload and store in MinIO
      operationId: complete_upload
      tags:
        - Upload
      parameters:
        - in: path
          name: object_id
          required: true
          schema:
            type: string
          description: Unique identifier for the upload session
      responses:
        "200":
          description: Upload complete and file stored in MinIO
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Confirmation message
        "404":
          description: File not found
...
