---
openapi: 3.0.2
info:
  version: 1.0.0
  title: Cloud Storage Handler
  description: API for handling objects on a cloud storage service
  contact:
    name: ELIXIR Cloud & AAI
    email: cloud-service@elixir-europe.org
  license:
    name: Apache 2.0
    url: >
      https://github.com/elixir-cloud-aai/
      cloud-storage-handler/blob/main/LICENSE
servers:
  - url: /elixircloud/csh/v1
paths:
  /object:
    post:
      operationId: upload_object
      summary: Upload a object
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '201':
          description: object uploaded successfully
        '400':
          description: Bad request
        '409':
          description: Conflict - object already exists
        '500':
          description: Internal server error
  /object/{resourceId}:
    head:
      operationId: object_upload_chunk_head
      summary: Check upload status of a object
      parameters:
        - name: resourceId
          in: path
          required: true
          description: ID of the resource
          schema:
            type: string
      responses:
        '200':
          description: object exists and offset returned
        '404':
          description: object not found
        '500':
          description: Internal server error
    patch:
      operationId: object_upload_chunk_patch
      summary: Upload a chunk of a object
      parameters:
        - name: resourceId
          in: path
          required: true
          description: ID of the resource
          schema:
            type: string
      requestBody:
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
      responses:
        '204':
          description: Chunk uploaded successfully
        '404':
          description: object not found
        '500':
          description: Internal server error
    delete:
      operationId: object_upload_chunk_delete
      summary: Delete a object
      parameters:
        - name: resourceId
          in: path
          required: true
          description: ID of the resource
          schema:
            type: string
      responses:
        '204':
          description: object deleted successfully
        '404':
          description: object not found
        '500':
          description: Internal server error
...
