---
openapi: 3.0.2
info:
  version: 1.0.0
  title: Cloud Storage Handler
  description: API for handling files on a cloud storage service
  contact:
    name: ELIXIR Cloud & AAI
    email: cloud-service@elixir-europe.org
  license:
    name: Apache 2.0
    url: >
      https://github.com/elixir-cloud-aai/
      cloud-storage-handler/blob/main/LICENSE
servers:
  - url: /elixircoud/csh/v1
paths:
  /:
    get:
      description: |
        Returns a welcome message
      operationId: home
      responses:
        '200':
          description: basic response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to Cloud Storage Handler API"
        '400':
          description: The request is malformed.
        '500':
          description: An unexpected error occurred.
  /list_files:
    get:
      description: |
        Returns a list of all files in the minio bucket
      operationId: list_files
      responses:
        '200':
          description: The list of files has been retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: The request is malformed.
        '500':
          description: An unexpected error occurred.
...
