---
openapi: 3.0.2
info:
  version: 1.0.0
  title: Cloud Storage Handler
  description: API for handling files on a cloud storage service
  contact:
    name: ELIXIR Cloud & AAI
    email: cloud-service@elixir-europe.org
  license:
    name: Apache 2.0
    url: >
      https://github.com/elixir-cloud-aai/
      cloud-storage-handler/blob/main/LICENSE
servers:
  - url: /elixircloud/csh/v1
paths:
  /:
    get:
      description: |
        Returns a welcome message
      operationId: home
      responses:
        '200':
          description: basic response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Welcome to Cloud Storage Handler API"
        '400':
          description: The request is malformed.
        '500':
          description: An unexpected error occurred.
...
  # /file-upload:
  #   post:
  #     operationId: tus_file_upload
  #     summary: Upload a file
  #     requestBody:
  #       content:
  #         application/octet-stream:
  #           schema:
  #             type: string
  #             format: binary
  #     responses:
  #       '201':
  #         description: File uploaded successfully
  #       '400':
  #         description: Bad request
  #       '409':
  #         description: Conflict - file already exists
  #       '500':
  #         description: Internal server error
  #   get:
  #     operationId: list_files
  #     summary: List all files
  #     responses:
  #       '200':
  #         description: List of files retrieved successfully
  #       '500':
  #         description: Internal server error

  # /file-upload/{resourceId}:
  #   head:
  #     operationId: tus_file_upload_chunk
  #     summary: Check upload status of a file
  #     parameters:
  #       - name: resourceId
  #         in: path
  #         required: true
  #         description: ID of the resource
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: File exists and offset returned
  #       '404':
  #         description: File not found
  #       '500':
  #         description: Internal server error
  #   patch:
  #     operationId: tus_file_upload_chunk
  #     summary: Upload a chunk of a file
  #     parameters:
  #       - name: resourceId
  #         in: path
  #         required: true
  #         description: ID of the resource
  #         schema:
  #           type: string
  #     requestBody:
  #       content:
  #         application/octet-stream:
  #           schema:
  #             type: string
  #             format: binary
  #     responses:
  #       '204':
  #         description: Chunk uploaded successfully
  #       '404':
  #         description: File not found
  #       '500':
  #         description: Internal server error
  #   delete:
  #     operationId: tus_file_upload_chunk
  #     summary: Delete a file
  #     parameters:
  #       - name: resourceId
  #         in: path
  #         required: true
  #         description: ID of the resource
  #         schema:
  #           type: string
  #     responses:
  #       '204':
  #         description: File deleted successfully
  #       '404':
  #         description: File not found
  #       '500':
  #         description: Internal server error

  # /file-upload/{resourceId}/download:
  #   get:
  #     operationId: tus_file_download
  #     summary: Download a file
  #     parameters:
  #       - name: resourceId
  #         in: path
  #         required: true
  #         description: ID of the resource
  #         schema:
  #           type: string
  #     responses:
  #       '200':
  #         description: File downloaded successfully
  #       '404':
  #         description: File not found
  #       '500':
  #         description: Internal server error